[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
elf = { version = "=0.7.4", default-features = false }

[profile.dev]
debug = true
opt-level = 0

[profile.release]
debug = true
opt-level = 3

[lib]
test = false
bench = false